spring.application.name=portfolio
spring.datasource.url=jdbc:postgresql://ep-wild-king-aqjvpivm-pooler.c-8.us-east-1.aws.neon.tech/portfolio?sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_M80lVGIdovha

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.connection-timeout=20000

spring.sql.init.mode=always